[package]
name = "xorq-datafusion"
version = "0.2.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xorq_datafusion"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.50", features = ["macros", "rt", "rt-multi-thread", "sync"] }
pyo3 = { version = "0.28", features = ["extension-module", "abi3", "abi3-py38"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"]}
datafusion =  { version = "53", features = ["avro", "unicode_expressions"]}
datafusion-common = { version = "53" }
datafusion-expr = "53"
prost = "0.14.3"
datafusion-optimizer = "53"
datafusion-sql = "53"
futures = "0.3"
async-trait = "=0.1.89"
arrow = { version = "58", features = ["pyarrow"] }
arrow-ord = "58"
aws-config = "=0.101.0"
aws-credential-types = "=0.101.0"
object_store = { version = "0.13.1", features = ["aws", "gcp", "http"] }
url = "2.5.7"

[profile.release]
lto = "thin"
codegen-units = 2
strip = true
